#!/bin/bash
# scripts/inject-secrets.sh
# Reads .env variables and writes them to ios/Shared/Secrets.swift

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$PROJECT_ROOT/.env"
OUTPUT_FILE="$PROJECT_ROOT/ios/Shared/Secrets.swift"

# Default values
API_KEY=""
MODEL="gemini-1.5-flash"

if [ -f "$ENV_FILE" ]; then
    echo "Found .env file, extracting secrets..."
    
    # Read GEMINI_API_KEY, removing carriage returns, quotes, and trailing comments
    KEY_VAL=$(grep -E "^GEMINI_API_KEY=" "$ENV_FILE" | head -n 1 | cut -d'=' -f2-)
    KEY_VAL=$(echo "$KEY_VAL" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e 's/^["'\''\\]*//' -e 's/["'\''\\]*$//' -e 's/#.*$//' -e 's/[[:space:]]*$//')
    
    if [ "$KEY_VAL" != "YOUR_API_KEY_HERE" ] && [ ! -z "$KEY_VAL" ]; then
        API_KEY="$KEY_VAL"
    fi
    
    # Read GEMINI_MODEL
    MODEL_VAL=$(grep -E "^GEMINI_MODEL=" "$ENV_FILE" | head -n 1 | cut -d'=' -f2-)
    MODEL_VAL=$(echo "$MODEL_VAL" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e 's/^["'\''\\]*//' -e 's/["'\''\\]*$//' -e 's/#.*$//' -e 's/[[:space:]]*$//')
    
    if [ ! -z "$MODEL_VAL" ]; then
        MODEL="$MODEL_VAL"
    fi
fi

# Ensure target Shared folder exists
mkdir -p "$(dirname "$OUTPUT_FILE")"

# Generate Swift Secrets struct
cat <<EOF > "$OUTPUT_FILE"
// This file is auto-generated by scripts/inject-secrets.sh.
// Do not modify this file directly or commit it to version control.
import Foundation

public struct Secrets {
    public static let geminiApiKey = "$API_KEY"
    public static let geminiModel = "$MODEL"
}
EOF

echo "Generated Secrets.swift successfully!"
